// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TAction;

privileged aspect TAction_Roo_JavaBean {
    
    public String TAction.getLib_action() {
        return this.lib_action;
    }
    
    public void TAction.setLib_action(String lib_action) {
        this.lib_action = lib_action;
    }
    
}
