// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TAxeDet;

privileged aspect TAxeDet_Roo_JavaBean {
    
    public String TAxeDet.getLib_axe_det() {
        return this.lib_axe_det;
    }
    
    public void TAxeDet.setLib_axe_det(String lib_axe_det) {
        this.lib_axe_det = lib_axe_det;
    }
    
}
