// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TClasse;

privileged aspect TClasse_Roo_JavaBean {
    
    public String TClasse.getLib_classe() {
        return this.lib_classe;
    }
    
    public void TClasse.setLib_classe(String lib_classe) {
        this.lib_classe = lib_classe;
    }
    
}
