// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TGroupe;

privileged aspect TGroupe_Roo_JavaBean {
    
    public String TGroupe.getLib_groupe() {
        return this.lib_groupe;
    }
    
    public void TGroupe.setLib_groupe(String lib_groupe) {
        this.lib_groupe = lib_groupe;
    }
    
}
