// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TImputBudgetaire;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TImputBudgetaire_Roo_Configurable {
    
    declare @type: TImputBudgetaire: @Configurable;
    
}
