// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TLigne;

privileged aspect TLigne_Roo_JavaBean {
    
    public String TLigne.getLib_ligne() {
        return this.lib_ligne;
    }
    
    public void TLigne.setLib_ligne(String lib_ligne) {
        this.lib_ligne = lib_ligne;
    }
    
}
