// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TRegion;

privileged aspect TRegion_Roo_JavaBean {
    
    public String TRegion.getLib_region() {
        return this.lib_region;
    }
    
    public void TRegion.setLib_region(String lib_region) {
        this.lib_region = lib_region;
    }
    
}
