// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.mef.sigfip.elaboration;

import com.mef.sigfip.elaboration.TSourceFin;

privileged aspect TSourceFin_Roo_JavaBean {
    
    public String TSourceFin.getLib_sf() {
        return this.lib_sf;
    }
    
    public void TSourceFin.setLib_sf(String lib_sf) {
        this.lib_sf = lib_sf;
    }
    
}
